version: '3.2'
services:
  #NGINX
  nginx:
    container_name: Nginx
    build:
      context: ./
      dockerfile: ./config/laravel/nginx/Dockerfile
    volumes:
      - ${PROJECT_DIR}:/var/www
      - ./logs/nginx:/var/log/nginx
    restart: always
    ports:
      - ${PORT_NGINX}:80
    links:
      - php-fpm
    networks:
      development_net:
          ipv4_address: ${IP_NGINX}
  #PHP-FPM
  php-fpm:
    container_name: Php-Fpm
    build:
      context: ./
      dockerfile: ./config/laravel/php-fpm/Dockerfile
    volumes:
      - ${PROJECT_DIR}:/var/www
      - ./config/laravel/php-fpm/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
      - ./logs/laravel/php-fpm:/var/log
    environment:
      - DB_USERNAME=${MYSQL_ROOT_PASSWORD}
      - DB_PASSWORD=${MYSQL_USER}
      - DB_HOST=${IP_MYSQL}
      - DB_DATABASE=${DB_DATABASE}
    restart: always
    ports:
      - ${PORT_PHPFPM}:9000
    networks:
      development_net:
          ipv4_address: ${IP_PHPFPM}

networks:
  development_net:
      ipam:
          driver: default
          config:
              - subnet: ${SUBNET}