version: '3'
services:
  #NGINX
  nginx:
    container_name: Nginx
    build:
      context: ./
      dockerfile: ./config/laravel/nginx/Dockerfile
    volumes:
      - ../laravel_project:/var/www
    ports:
      - 8095:80
    links:
      - php-fpm
  #PHP-FPM
  php-fpm:
    container_name: Php-Fpm
    build:
      context: ./
      dockerfile: ./config/laravel/php-fpm/Dockerfile
    volumes:
      - ../laravel_project:/var/www
    ports:
      - 9000:9000