version: '2'
services:
  # MySql 5.7
  mysql5.7:
    image: mysql:5.7
    container_name: mysql-5.7
    volumes:
      - "./data/mysql_5.7:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - mysql5.7
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    volumes:
      - "./config/phpmyadmin/themes/fallen/:/var/www/html/themes/fallen/"
      - "./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    links:
      - mysql5.7:mysql
    ports:
     - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql5.7