version: "3.2"
services:
  # MySql 5.7
  mysql:
    build:
      context: ./
      dockerfile: ./config/mysql/Dockerfile
    container_name: MySql
    volumes:
      - ./data/mysql_5.7:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    restart: always
    ports:
      - ${PORT_MYSQL}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      development_net:
        ipv4_address: ${IP_MYSQL}
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && chmod -R 777 /var/log/mysql && exec /entrypoint.sh mysqld"
  # Maria DB
  mariadb:
    build:
      context: ./
      dockerfile: ./config/mariadb/Dockerfile
    container_name: MariaDB
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    restart: always
    ports:
      - ${PORT_MARIADB}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      development_net:
        ipv4_address: ${IP_MARIADB}
  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5.1
    container_name: PhpMyAdmin
    volumes:
      - ./config/phpmyadmin/themes/darkwolf/:/var/www/html/themes/darkwolf/
      - ./config/phpmyadmin/user/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:rw
      - ./config/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini:rw
    links:
      - mysql:mysql
    restart: always
    ports:
      - ${PORT_PHPMYADMIN}:80
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOSTS: mysql,mariadb
      UPLOAD_LIMIT: 1280M
    networks:
      development_net:
        ipv4_address: ${IP_PHPMYADMIN}

networks:
  development_net:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
