version: '3'
services:
  #PHP
  php5-fpm:
    container_name: Php5-Fpm
    build:
      context: ./
      dockerfile: ./config/php_5/php-fpm/Dockerfile
      args:
        TEXT_ENV: ${NODE_ENV}
    volumes:
      - ${PHP_PROJECT_DIR}:/var/www
      - ./config/php_5/php-fpm/php5.ini:/usr/local/etc/php/conf.d/php5.ini
      - ./logs/php_5/php-fpm:/var/log
    restart: always
    environment:
      NODE_ENV: production
    networks:
      development_net:
          ipv4_address: ${IP_PHP5_NGINX}
  #Nginx
  nginx-php5:
    container_name: Php5-App
    build:
        context: ./
        dockerfile: ./config/php_5/nginx/Dockerfile
    volumes:
      - ${PHP_PROJECT_DIR}:/var/www
      - ./logs/php_5/nginx:/var/log/nginx
      - ./config/php_5/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php5-fpm
    links:
      - php5-fpm
    restart: always
    ports:
      - ${PORT_PHP5_APP}:80
      - 443:443
    environment:
      NODE_ENV: ${PHP_PROJECT_DIR}
    networks:
      development_net:
          ipv4_address: ${IP_PHP5FPM}
networks:
  development_net:
      ipam:
          driver: default
          config:
              - subnet: ${SUBNET}