version: '3.3'
services:
  #PostgreSQL Database
  postgreSQL:
    image: postgres:12
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./data/postgresql_data:/var/lib/postgresql/data
    networks:
      - development_net
  #Adminer
  adminer:
    image: adminer
    container_name: Adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgreSQL
    networks:
      - development_net
networks:
  development_net:
      ipam:
          driver: default
          config:
              - subnet: ${SUBNET}